### ISSUE TITLE
Support for extended palette

### ISSUE THREAD

**Issue by ElfEars** [0xcafed00d/tac08#3]
In the new versions of pico-8 there are some secret POKEs that you can do to access an alternate darker/warmer/autumny 16 color palette. You can only have 16 colors onscreen per frame but you can mix and match from both palettes as you please.

You poke the regular color palette registers in the draw state (0x5F10-0x5F1F) as normal but add 128.
You can also do this by using pal(color_to_replace,new_color+128,1)
POKEing 0x5F2E with 1 will help with testing this as it prevents the colors from resetting after the program ends.

![extpal p8](https://user-images.githubusercontent.com/20967774/66089773-8c0cdc00-e578-11e9-85ca-b5142e59ed14.png)

Here's a link to the extended colors: https://lospec.com/palette-list/pico-8-secret-palette
They look pretty accurate although I haven't checked if they're exact

**Comment by 0xcafed00d** [comment]
Hi ElfEars, thanks for raising this issue. 
Support for the extended palette is on my TODO list along with the extended font that will be in the next version of pico8. I hope to be able to get to this soon. 

On a side note, tac08 allows setting the palette to entries to any RGB value via the use of its extended api. (along with many other functions) see the (incomplete - sorry) extended api document here:
https://github.com/0xcafed00d/tac08/blob/master/extended_api.md
example:
```lua
    __tac08__.setpal(7, 255, 255, 128)
```

**Comment by 0xcafed00d** [comment]
now supports extended palette
